inputSpec: doc-openapi-cert-manager-2.13.0.yaml
generatorName: go
outputDir: internal/issuer/czertainly
generateApiTests: false
generateModelTests: false
generateModelDocumentation: false
generateApiDocumentation: false
additionalProperties:
  packageName: czertainly
  isGoSubmodule: false
  disallowAdditionalPropertiesIfNotPresent: false
  enumClassPrefix: true
  withGoMod: false
