apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "czertainly-issuer.labels" . | nindent 4 }}
  name: cert-manager-controller-approve:czertainly-issuer-czertainly-com
rules:
  - apiGroups:
      - cert-manager.io
    resources:
      - signers
    verbs:
      - approve
    resourceNames:
      - issuers.czertainly-issuer.czertainly.com/*
      - clusterissuers.czertainly-issuer.czertainly.com/*
