---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - czertainly-issuer.czertainly.com
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - czertainly-issuer.czertainly.com
  resources:
  - clusterissuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - czertainly-issuer.czertainly.com
  resources:
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - czertainly-issuer.czertainly.com
  resources:
  - issuers/status
  verbs:
  - get
  - patch
  - update
