/*
CZERTAINLY Cert Manager

REST API for implementations of cert-manager issuer

API version: 2.15.0
Contact: info@czertainly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package czertainly

import (
	"encoding/json"
	"fmt"
)

// checks if the CertificateRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateRequestDto{}

// CertificateRequestDto struct for CertificateRequestDto
type CertificateRequestDto struct {
	// Certificate type
	CertificateType CertificateType `json:"certificateType"`
	// Certificate request format
	CertificateRequestFormat CertificateRequestFormat `json:"certificateRequestFormat"`
	// Public key algorithm
	PublicKeyAlgorithm string `json:"publicKeyAlgorithm"`
	// Certificate signature algorithm
	SignatureAlgorithm string `json:"signatureAlgorithm"`
	// Certificate alternative signature algorithm
	AltSignatureAlgorithm *string `json:"altSignatureAlgorithm,omitempty"`
	// Certificate request content
	Content string `json:"content"`
	// Certificate common name
	CommonName string `json:"commonName"`
	// Subject DN of the Certificate
	SubjectDn string `json:"subjectDn"`
	// Subject alternative names
	SubjectAlternativeNames map[string][]string `json:"subjectAlternativeNames,omitempty"`
	// CSR Attributes
	Attributes []ResponseAttributeDto `json:"attributes,omitempty"`
	// Signature Attributes
	SignatureAttributes []ResponseAttributeDto `json:"signatureAttributes,omitempty"`
	// Alternative Signature Attributes
	AltSignatureAttributes []ResponseAttributeDto `json:"altSignatureAttributes,omitempty"`
	// UUID of the Key
	KeyUuid *string `json:"keyUuid,omitempty"`
	// UUID of the Alternative Key
	AltKeyUuid *string `json:"altKeyUuid,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CertificateRequestDto CertificateRequestDto

// NewCertificateRequestDto instantiates a new CertificateRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateRequestDto(certificateType CertificateType, certificateRequestFormat CertificateRequestFormat, publicKeyAlgorithm string, signatureAlgorithm string, content string, commonName string, subjectDn string) *CertificateRequestDto {
	this := CertificateRequestDto{}
	this.CertificateType = certificateType
	this.CertificateRequestFormat = certificateRequestFormat
	this.PublicKeyAlgorithm = publicKeyAlgorithm
	this.SignatureAlgorithm = signatureAlgorithm
	this.Content = content
	this.CommonName = commonName
	this.SubjectDn = subjectDn
	return &this
}

// NewCertificateRequestDtoWithDefaults instantiates a new CertificateRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateRequestDtoWithDefaults() *CertificateRequestDto {
	this := CertificateRequestDto{}
	return &this
}

// GetCertificateType returns the CertificateType field value
func (o *CertificateRequestDto) GetCertificateType() CertificateType {
	if o == nil {
		var ret CertificateType
		return ret
	}

	return o.CertificateType
}

// GetCertificateTypeOk returns a tuple with the CertificateType field value
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetCertificateTypeOk() (*CertificateType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CertificateType, true
}

// SetCertificateType sets field value
func (o *CertificateRequestDto) SetCertificateType(v CertificateType) {
	o.CertificateType = v
}

// GetCertificateRequestFormat returns the CertificateRequestFormat field value
func (o *CertificateRequestDto) GetCertificateRequestFormat() CertificateRequestFormat {
	if o == nil {
		var ret CertificateRequestFormat
		return ret
	}

	return o.CertificateRequestFormat
}

// GetCertificateRequestFormatOk returns a tuple with the CertificateRequestFormat field value
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetCertificateRequestFormatOk() (*CertificateRequestFormat, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CertificateRequestFormat, true
}

// SetCertificateRequestFormat sets field value
func (o *CertificateRequestDto) SetCertificateRequestFormat(v CertificateRequestFormat) {
	o.CertificateRequestFormat = v
}

// GetPublicKeyAlgorithm returns the PublicKeyAlgorithm field value
func (o *CertificateRequestDto) GetPublicKeyAlgorithm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKeyAlgorithm
}

// GetPublicKeyAlgorithmOk returns a tuple with the PublicKeyAlgorithm field value
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetPublicKeyAlgorithmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicKeyAlgorithm, true
}

// SetPublicKeyAlgorithm sets field value
func (o *CertificateRequestDto) SetPublicKeyAlgorithm(v string) {
	o.PublicKeyAlgorithm = v
}

// GetSignatureAlgorithm returns the SignatureAlgorithm field value
func (o *CertificateRequestDto) GetSignatureAlgorithm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignatureAlgorithm
}

// GetSignatureAlgorithmOk returns a tuple with the SignatureAlgorithm field value
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetSignatureAlgorithmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignatureAlgorithm, true
}

// SetSignatureAlgorithm sets field value
func (o *CertificateRequestDto) SetSignatureAlgorithm(v string) {
	o.SignatureAlgorithm = v
}

// GetAltSignatureAlgorithm returns the AltSignatureAlgorithm field value if set, zero value otherwise.
func (o *CertificateRequestDto) GetAltSignatureAlgorithm() string {
	if o == nil || IsNil(o.AltSignatureAlgorithm) {
		var ret string
		return ret
	}
	return *o.AltSignatureAlgorithm
}

// GetAltSignatureAlgorithmOk returns a tuple with the AltSignatureAlgorithm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetAltSignatureAlgorithmOk() (*string, bool) {
	if o == nil || IsNil(o.AltSignatureAlgorithm) {
		return nil, false
	}
	return o.AltSignatureAlgorithm, true
}

// HasAltSignatureAlgorithm returns a boolean if a field has been set.
func (o *CertificateRequestDto) HasAltSignatureAlgorithm() bool {
	if o != nil && !IsNil(o.AltSignatureAlgorithm) {
		return true
	}

	return false
}

// SetAltSignatureAlgorithm gets a reference to the given string and assigns it to the AltSignatureAlgorithm field.
func (o *CertificateRequestDto) SetAltSignatureAlgorithm(v string) {
	o.AltSignatureAlgorithm = &v
}

// GetContent returns the Content field value
func (o *CertificateRequestDto) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *CertificateRequestDto) SetContent(v string) {
	o.Content = v
}

// GetCommonName returns the CommonName field value
func (o *CertificateRequestDto) GetCommonName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommonName
}

// GetCommonNameOk returns a tuple with the CommonName field value
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetCommonNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommonName, true
}

// SetCommonName sets field value
func (o *CertificateRequestDto) SetCommonName(v string) {
	o.CommonName = v
}

// GetSubjectDn returns the SubjectDn field value
func (o *CertificateRequestDto) GetSubjectDn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectDn
}

// GetSubjectDnOk returns a tuple with the SubjectDn field value
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetSubjectDnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectDn, true
}

// SetSubjectDn sets field value
func (o *CertificateRequestDto) SetSubjectDn(v string) {
	o.SubjectDn = v
}

// GetSubjectAlternativeNames returns the SubjectAlternativeNames field value if set, zero value otherwise.
func (o *CertificateRequestDto) GetSubjectAlternativeNames() map[string][]string {
	if o == nil || IsNil(o.SubjectAlternativeNames) {
		var ret map[string][]string
		return ret
	}
	return o.SubjectAlternativeNames
}

// GetSubjectAlternativeNamesOk returns a tuple with the SubjectAlternativeNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetSubjectAlternativeNamesOk() (map[string][]string, bool) {
	if o == nil || IsNil(o.SubjectAlternativeNames) {
		return map[string][]string{}, false
	}
	return o.SubjectAlternativeNames, true
}

// HasSubjectAlternativeNames returns a boolean if a field has been set.
func (o *CertificateRequestDto) HasSubjectAlternativeNames() bool {
	if o != nil && !IsNil(o.SubjectAlternativeNames) {
		return true
	}

	return false
}

// SetSubjectAlternativeNames gets a reference to the given map[string][]string and assigns it to the SubjectAlternativeNames field.
func (o *CertificateRequestDto) SetSubjectAlternativeNames(v map[string][]string) {
	o.SubjectAlternativeNames = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *CertificateRequestDto) GetAttributes() []ResponseAttributeDto {
	if o == nil || IsNil(o.Attributes) {
		var ret []ResponseAttributeDto
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetAttributesOk() ([]ResponseAttributeDto, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *CertificateRequestDto) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []ResponseAttributeDto and assigns it to the Attributes field.
func (o *CertificateRequestDto) SetAttributes(v []ResponseAttributeDto) {
	o.Attributes = v
}

// GetSignatureAttributes returns the SignatureAttributes field value if set, zero value otherwise.
func (o *CertificateRequestDto) GetSignatureAttributes() []ResponseAttributeDto {
	if o == nil || IsNil(o.SignatureAttributes) {
		var ret []ResponseAttributeDto
		return ret
	}
	return o.SignatureAttributes
}

// GetSignatureAttributesOk returns a tuple with the SignatureAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetSignatureAttributesOk() ([]ResponseAttributeDto, bool) {
	if o == nil || IsNil(o.SignatureAttributes) {
		return nil, false
	}
	return o.SignatureAttributes, true
}

// HasSignatureAttributes returns a boolean if a field has been set.
func (o *CertificateRequestDto) HasSignatureAttributes() bool {
	if o != nil && !IsNil(o.SignatureAttributes) {
		return true
	}

	return false
}

// SetSignatureAttributes gets a reference to the given []ResponseAttributeDto and assigns it to the SignatureAttributes field.
func (o *CertificateRequestDto) SetSignatureAttributes(v []ResponseAttributeDto) {
	o.SignatureAttributes = v
}

// GetAltSignatureAttributes returns the AltSignatureAttributes field value if set, zero value otherwise.
func (o *CertificateRequestDto) GetAltSignatureAttributes() []ResponseAttributeDto {
	if o == nil || IsNil(o.AltSignatureAttributes) {
		var ret []ResponseAttributeDto
		return ret
	}
	return o.AltSignatureAttributes
}

// GetAltSignatureAttributesOk returns a tuple with the AltSignatureAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetAltSignatureAttributesOk() ([]ResponseAttributeDto, bool) {
	if o == nil || IsNil(o.AltSignatureAttributes) {
		return nil, false
	}
	return o.AltSignatureAttributes, true
}

// HasAltSignatureAttributes returns a boolean if a field has been set.
func (o *CertificateRequestDto) HasAltSignatureAttributes() bool {
	if o != nil && !IsNil(o.AltSignatureAttributes) {
		return true
	}

	return false
}

// SetAltSignatureAttributes gets a reference to the given []ResponseAttributeDto and assigns it to the AltSignatureAttributes field.
func (o *CertificateRequestDto) SetAltSignatureAttributes(v []ResponseAttributeDto) {
	o.AltSignatureAttributes = v
}

// GetKeyUuid returns the KeyUuid field value if set, zero value otherwise.
func (o *CertificateRequestDto) GetKeyUuid() string {
	if o == nil || IsNil(o.KeyUuid) {
		var ret string
		return ret
	}
	return *o.KeyUuid
}

// GetKeyUuidOk returns a tuple with the KeyUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetKeyUuidOk() (*string, bool) {
	if o == nil || IsNil(o.KeyUuid) {
		return nil, false
	}
	return o.KeyUuid, true
}

// HasKeyUuid returns a boolean if a field has been set.
func (o *CertificateRequestDto) HasKeyUuid() bool {
	if o != nil && !IsNil(o.KeyUuid) {
		return true
	}

	return false
}

// SetKeyUuid gets a reference to the given string and assigns it to the KeyUuid field.
func (o *CertificateRequestDto) SetKeyUuid(v string) {
	o.KeyUuid = &v
}

// GetAltKeyUuid returns the AltKeyUuid field value if set, zero value otherwise.
func (o *CertificateRequestDto) GetAltKeyUuid() string {
	if o == nil || IsNil(o.AltKeyUuid) {
		var ret string
		return ret
	}
	return *o.AltKeyUuid
}

// GetAltKeyUuidOk returns a tuple with the AltKeyUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateRequestDto) GetAltKeyUuidOk() (*string, bool) {
	if o == nil || IsNil(o.AltKeyUuid) {
		return nil, false
	}
	return o.AltKeyUuid, true
}

// HasAltKeyUuid returns a boolean if a field has been set.
func (o *CertificateRequestDto) HasAltKeyUuid() bool {
	if o != nil && !IsNil(o.AltKeyUuid) {
		return true
	}

	return false
}

// SetAltKeyUuid gets a reference to the given string and assigns it to the AltKeyUuid field.
func (o *CertificateRequestDto) SetAltKeyUuid(v string) {
	o.AltKeyUuid = &v
}

func (o CertificateRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["certificateType"] = o.CertificateType
	toSerialize["certificateRequestFormat"] = o.CertificateRequestFormat
	toSerialize["publicKeyAlgorithm"] = o.PublicKeyAlgorithm
	toSerialize["signatureAlgorithm"] = o.SignatureAlgorithm
	if !IsNil(o.AltSignatureAlgorithm) {
		toSerialize["altSignatureAlgorithm"] = o.AltSignatureAlgorithm
	}
	toSerialize["content"] = o.Content
	toSerialize["commonName"] = o.CommonName
	toSerialize["subjectDn"] = o.SubjectDn
	if !IsNil(o.SubjectAlternativeNames) {
		toSerialize["subjectAlternativeNames"] = o.SubjectAlternativeNames
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.SignatureAttributes) {
		toSerialize["signatureAttributes"] = o.SignatureAttributes
	}
	if !IsNil(o.AltSignatureAttributes) {
		toSerialize["altSignatureAttributes"] = o.AltSignatureAttributes
	}
	if !IsNil(o.KeyUuid) {
		toSerialize["keyUuid"] = o.KeyUuid
	}
	if !IsNil(o.AltKeyUuid) {
		toSerialize["altKeyUuid"] = o.AltKeyUuid
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CertificateRequestDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"certificateType",
		"certificateRequestFormat",
		"publicKeyAlgorithm",
		"signatureAlgorithm",
		"content",
		"commonName",
		"subjectDn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertificateRequestDto := _CertificateRequestDto{}

	err = json.Unmarshal(data, &varCertificateRequestDto)

	if err != nil {
		return err
	}

	*o = CertificateRequestDto(varCertificateRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "certificateType")
		delete(additionalProperties, "certificateRequestFormat")
		delete(additionalProperties, "publicKeyAlgorithm")
		delete(additionalProperties, "signatureAlgorithm")
		delete(additionalProperties, "altSignatureAlgorithm")
		delete(additionalProperties, "content")
		delete(additionalProperties, "commonName")
		delete(additionalProperties, "subjectDn")
		delete(additionalProperties, "subjectAlternativeNames")
		delete(additionalProperties, "attributes")
		delete(additionalProperties, "signatureAttributes")
		delete(additionalProperties, "altSignatureAttributes")
		delete(additionalProperties, "keyUuid")
		delete(additionalProperties, "altKeyUuid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCertificateRequestDto struct {
	value *CertificateRequestDto
	isSet bool
}

func (v NullableCertificateRequestDto) Get() *CertificateRequestDto {
	return v.value
}

func (v *NullableCertificateRequestDto) Set(val *CertificateRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateRequestDto(val *CertificateRequestDto) *NullableCertificateRequestDto {
	return &NullableCertificateRequestDto{value: val, isSet: true}
}

func (v NullableCertificateRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


