/*
CZERTAINLY Cert Manager

REST API for implementations of cert-manager issuer

API version: 2.15.0
Contact: info@czertainly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package czertainly

import (
	"encoding/json"
	"fmt"
)

// checks if the ResponseAttributeDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseAttributeDto{}

// ResponseAttributeDto Response attribute with content for object it belongs to
type ResponseAttributeDto struct {
	// UUID of the Attribute
	Uuid *string `json:"uuid,omitempty"`
	// Name of the Attribute
	Name string `json:"name"`
	// Label of the the Attribute
	Label string `json:"label"`
	// Type of the Attribute
	Type AttributeType `json:"type"`
	// Content Type of the Attribute
	ContentType AttributeContentType `json:"contentType"`
	// Content of the Attribute
	Content []BaseAttributeContentDto `json:"content,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ResponseAttributeDto ResponseAttributeDto

// NewResponseAttributeDto instantiates a new ResponseAttributeDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseAttributeDto(name string, label string, type_ AttributeType, contentType AttributeContentType) *ResponseAttributeDto {
	this := ResponseAttributeDto{}
	this.Name = name
	this.Label = label
	this.Type = type_
	this.ContentType = contentType
	return &this
}

// NewResponseAttributeDtoWithDefaults instantiates a new ResponseAttributeDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseAttributeDtoWithDefaults() *ResponseAttributeDto {
	this := ResponseAttributeDto{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *ResponseAttributeDto) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseAttributeDto) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *ResponseAttributeDto) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *ResponseAttributeDto) SetUuid(v string) {
	o.Uuid = &v
}

// GetName returns the Name field value
func (o *ResponseAttributeDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ResponseAttributeDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ResponseAttributeDto) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value
func (o *ResponseAttributeDto) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ResponseAttributeDto) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ResponseAttributeDto) SetLabel(v string) {
	o.Label = v
}

// GetType returns the Type field value
func (o *ResponseAttributeDto) GetType() AttributeType {
	if o == nil {
		var ret AttributeType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ResponseAttributeDto) GetTypeOk() (*AttributeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ResponseAttributeDto) SetType(v AttributeType) {
	o.Type = v
}

// GetContentType returns the ContentType field value
func (o *ResponseAttributeDto) GetContentType() AttributeContentType {
	if o == nil {
		var ret AttributeContentType
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *ResponseAttributeDto) GetContentTypeOk() (*AttributeContentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *ResponseAttributeDto) SetContentType(v AttributeContentType) {
	o.ContentType = v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *ResponseAttributeDto) GetContent() []BaseAttributeContentDto {
	if o == nil || IsNil(o.Content) {
		var ret []BaseAttributeContentDto
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseAttributeDto) GetContentOk() ([]BaseAttributeContentDto, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *ResponseAttributeDto) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []BaseAttributeContentDto and assigns it to the Content field.
func (o *ResponseAttributeDto) SetContent(v []BaseAttributeContentDto) {
	o.Content = v
}

func (o ResponseAttributeDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseAttributeDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	toSerialize["name"] = o.Name
	toSerialize["label"] = o.Label
	toSerialize["type"] = o.Type
	toSerialize["contentType"] = o.ContentType
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResponseAttributeDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"label",
		"type",
		"contentType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseAttributeDto := _ResponseAttributeDto{}

	err = json.Unmarshal(data, &varResponseAttributeDto)

	if err != nil {
		return err
	}

	*o = ResponseAttributeDto(varResponseAttributeDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "name")
		delete(additionalProperties, "label")
		delete(additionalProperties, "type")
		delete(additionalProperties, "contentType")
		delete(additionalProperties, "content")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResponseAttributeDto struct {
	value *ResponseAttributeDto
	isSet bool
}

func (v NullableResponseAttributeDto) Get() *ResponseAttributeDto {
	return v.value
}

func (v *NullableResponseAttributeDto) Set(val *ResponseAttributeDto) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseAttributeDto) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseAttributeDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseAttributeDto(val *ResponseAttributeDto) *NullableResponseAttributeDto {
	return &NullableResponseAttributeDto{value: val, isSet: true}
}

func (v NullableResponseAttributeDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseAttributeDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


