/*
CZERTAINLY Cert Manager

REST API for implementations of cert-manager issuer

API version: 2.14.2-SNAPSHOT
Contact: info@czertainly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package czertainly

import (
	"encoding/json"
	"fmt"
)

// checks if the UserCertificateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCertificateDto{}

// UserCertificateDto struct for UserCertificateDto
type UserCertificateDto struct {
	// UUID of the certificate
	Uuid string `json:"uuid"`
	// Fingerprint of the certificate
	Fingerprint string `json:"fingerprint"`
	AdditionalProperties map[string]interface{}
}

type _UserCertificateDto UserCertificateDto

// NewUserCertificateDto instantiates a new UserCertificateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCertificateDto(uuid string, fingerprint string) *UserCertificateDto {
	this := UserCertificateDto{}
	this.Uuid = uuid
	this.Fingerprint = fingerprint
	return &this
}

// NewUserCertificateDtoWithDefaults instantiates a new UserCertificateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCertificateDtoWithDefaults() *UserCertificateDto {
	this := UserCertificateDto{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *UserCertificateDto) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *UserCertificateDto) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *UserCertificateDto) SetUuid(v string) {
	o.Uuid = v
}

// GetFingerprint returns the Fingerprint field value
func (o *UserCertificateDto) GetFingerprint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fingerprint
}

// GetFingerprintOk returns a tuple with the Fingerprint field value
// and a boolean to check if the value has been set.
func (o *UserCertificateDto) GetFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fingerprint, true
}

// SetFingerprint sets field value
func (o *UserCertificateDto) SetFingerprint(v string) {
	o.Fingerprint = v
}

func (o UserCertificateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCertificateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["fingerprint"] = o.Fingerprint

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserCertificateDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"fingerprint",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserCertificateDto := _UserCertificateDto{}

	err = json.Unmarshal(data, &varUserCertificateDto)

	if err != nil {
		return err
	}

	*o = UserCertificateDto(varUserCertificateDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "fingerprint")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserCertificateDto struct {
	value *UserCertificateDto
	isSet bool
}

func (v NullableUserCertificateDto) Get() *UserCertificateDto {
	return v.value
}

func (v *NullableUserCertificateDto) Set(val *UserCertificateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCertificateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCertificateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCertificateDto(val *UserCertificateDto) *NullableUserCertificateDto {
	return &NullableUserCertificateDto{value: val, isSet: true}
}

func (v NullableUserCertificateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCertificateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


