apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: czertainly-certificate
spec:
  secretName: czertainly-certificate
  commonName: czertainly-issuer-cert-manager
  issuerRef:
    name: clusterissuer-czertainly
    kind: ClusterIssuer
    group: czertainly-issuer.czertainly.com
