/*
CZERTAINLY Cert Manager

REST API for implementations of cert-manager issuer

API version: 2.13.0
Contact: info@czertainly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package czertainly

import (
	"encoding/json"
	"fmt"
)

// checks if the CodeBlockAttributeContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodeBlockAttributeContent{}

// CodeBlockAttributeContent struct for CodeBlockAttributeContent
type CodeBlockAttributeContent struct {
	// Content Reference
	Reference *string `json:"reference,omitempty"`
	Data CodeBlockAttributeContentData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _CodeBlockAttributeContent CodeBlockAttributeContent

// NewCodeBlockAttributeContent instantiates a new CodeBlockAttributeContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodeBlockAttributeContent(data CodeBlockAttributeContentData) *CodeBlockAttributeContent {
	this := CodeBlockAttributeContent{}
	this.Data = data
	return &this
}

// NewCodeBlockAttributeContentWithDefaults instantiates a new CodeBlockAttributeContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodeBlockAttributeContentWithDefaults() *CodeBlockAttributeContent {
	this := CodeBlockAttributeContent{}
	return &this
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *CodeBlockAttributeContent) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeBlockAttributeContent) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *CodeBlockAttributeContent) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *CodeBlockAttributeContent) SetReference(v string) {
	o.Reference = &v
}

// GetData returns the Data field value
func (o *CodeBlockAttributeContent) GetData() CodeBlockAttributeContentData {
	if o == nil {
		var ret CodeBlockAttributeContentData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CodeBlockAttributeContent) GetDataOk() (*CodeBlockAttributeContentData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CodeBlockAttributeContent) SetData(v CodeBlockAttributeContentData) {
	o.Data = v
}

func (o CodeBlockAttributeContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodeBlockAttributeContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CodeBlockAttributeContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodeBlockAttributeContent := _CodeBlockAttributeContent{}

	err = json.Unmarshal(data, &varCodeBlockAttributeContent)

	if err != nil {
		return err
	}

	*o = CodeBlockAttributeContent(varCodeBlockAttributeContent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "reference")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCodeBlockAttributeContent struct {
	value *CodeBlockAttributeContent
	isSet bool
}

func (v NullableCodeBlockAttributeContent) Get() *CodeBlockAttributeContent {
	return v.value
}

func (v *NullableCodeBlockAttributeContent) Set(val *CodeBlockAttributeContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCodeBlockAttributeContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCodeBlockAttributeContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodeBlockAttributeContent(val *CodeBlockAttributeContent) *NullableCodeBlockAttributeContent {
	return &NullableCodeBlockAttributeContent{value: val, isSet: true}
}

func (v NullableCodeBlockAttributeContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodeBlockAttributeContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


